import React, { useState } from 'react';
import '../App.css';
import BlogPost from './Blog/BlogPost';
import Image from '../assets/images/blog-mock-images/bench.jpg';
import ClockIcon from '../assets/svg/ClockIcon';

//Mock data
let posts = [
    { id: 1, date: `${timeStamp('2020', '0', '16', '23', '59')}`, heading: "Lorem Ipsum Color blablabla", introduction:"consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ullamcorper dignissim cras tincidunt lobortis. Amet porttitor eget dolor morbi.", entry:"Dvfdvfdvfdvdvfv cde dignissim enim sit."},
    { id: 2, date: `${timeStamp('2020', '1', '11', '1', '30')}`, heading: "Lorem Ipsum Color lalalalalal", introduction:"consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore.", entry:"Dweretyetteytrque dignissim enim sit."},
    { id: 3, date: `${timeStamp('2020', '1', '30', '9', '15')}`, heading: "Lorem Ipsum Color bobobobobbobo", introduction:"sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ullamcorper dignissim crolor morbi.", entry:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sed odio morbi quis commodo odio aenean sed adipiscing diam. Hendrerit gravida rutrum quisque non tellus orci ac. Maecenas ultricies mi eget mauris pharetra. Enim blandit volutpat maecenas volutpat blandit aliquam etiam. Sagittis aliquam malesuada bibendum arcu. Mauris pharetra et ultrices neque ornare. Pellentesque habitant morbi tristique senectus et netus et malesuada. Ullamcorper a lacus vestibulum sed arcu. Turpis tincidunt id aliquet risus feugiat. Risus viverra adipiscing at in tellus integer. Dui vivamus arcu felis bibendum ut. Non blandit massa enim nec dui nunc. Donec pretium vulputate sapien nec sagittis aliquam malesuada bibendum. Placerat vestibulum lectus mauris ultrices. Quis vel eros donec ac odio tempor. Non consectetur a erat nam at lectus urna duis. Tortor dignissim convallis aenean et tortor at risus. Integer quis auctor elit sed vulputate mi sit. Facilisis volutpat est velit egestas dui id. Integer eget aliquet nibh praesent tristique magna sit amet. Lobortis feugiat vivamus at augue eget. Metus dictum at tempor commodo ullamcorper a. Sapien nec sagittis aliquam malesuada bibendum arcu vitae elementum. Elementum eu facilisis sed odio morbi quis commodo odio aenean. Hendrerit dolor magna eget est lorem. Non odio euismod lacinia at quis. Quis blandit turpis cursus in hac habitasse platea dictumst quisque."},
    { id: 4, date: `${timeStamp('2020', '3', '11', '10', '10')}`, heading: "Lorem Ipsum Color unudslkkdslkfjdsjkfjkcs cdfssewswededes dscd", introduction:"sed csdcdscsdcsddo eiusmod tempor incididunt ut labore et dolore magna aliqua. Ullamcorper dignissim crolor morbi.", entry:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sed odio morbi quis commodo odio aenean sed adipiscing diam. Hendrerit gravida rutrum quisque non tellus orci ac. Maecenas ultricies mi eget mauris pharetra. Enim blandit volutpat maecenas volutpat blandit aliquam etiam. Sagittis aliquam malesuada bibendum arcu. Mauris pharetra et ultrices neque ornare. Pellentesque habitant morbi tristique senectus et netus et malesuada. Ullamcorper a lacus vestibulum sed arcu. Turpis tincidunt id aliquet risus feugiat. Risus viverra adipiscing at in tellus integer. Dui vivamus arcu felis bibendum ut. Non blandit massa enim nec dui nunc. Donec pretium vulputate sapien nec sagittis aliquam malesuada bibendum. Placerat vestibulum lectus mauris ultrices. Quis vel eros donec ac odio tempor. Non consectetur a erat nam at lectus urna duis. Tortor dignissim convallis aenean et tortor at risus. Facilisis volutpat est velit egestas dui id. Integer eget aliquet nibh praesent tristique magna sit amet. Lobortis feugiat vivamus at augue eget. Metus dictum at tempor commodo ullamcorper a. Sapien nec sagittis aliquam malesuada bibendum arcu vitae elementum. Elementum eu facilisis sed odio morbi quis commodo odio aenean. Hendrerit dolor magna eget est lorem. Non odio euismod lacinia at quis. Quis blandit turpis cursus in hac habitasse platea dictumst quisque."},
    { id: 5, date: `${timeStamp('2020', '4', '13', '7', '0')}`, heading: "Lorem Ipsum Color unudslkkdslkfjdsjkfjkcs ", introduction:"sed csdcdscsdcsddo eiusmod tempor incididunt ut labore et dolore magna aliqua. Ullamcorper dignissim crolor morbi.", entry:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sed odio morbi quis commodo odio aenean sed adipiscing diam. Hendrerit gravida rutrum quisque non tellus orci ac. Maecenas ultricies mi eget mauris pharetra. Enim blandit volutpat maecenas volutpat blandit aliquam etiam. Sagittis aliquam malesuada bibendum arcu. Mauris pharetra et ultrices neque ornare. Pellentesque habitant morbi tristique senectus et netus et malesuada. Ullamcorper a lacus vestibulum sed arcu. Turpis tincidunt id aliquet risus feugiat. Risus viverra adipiscing at in tellus integer. Dui vivamus arcu felis bibendum ut. Non blandit massa enim nec dui nunc. Donec pretium vulputate sapien nec sagittis aliquam malesuada bibendum. Placerat vestibulum lectus mauris ultrices. Quis vel eros donec ac odio tempor. Non consectetur a erat nam at lectus urna duis. Tortor dignissim convallis aenean et tortor at risus. Facilisis volutpat est velit egestas dui id. Integer eget aliquet nibh praesent tristique magna sit amet. Lobortis feugiat vivamus at augue eget. Metus dictum at tempor commodo ullamcorper a. Sapien nec sagittis aliquam malesuada bibendum arcu vitae elementum. Elementum eu facilisis sed odio morbi quis commodo odio aenean. Hendrerit dolor magna eget est lorem. Non odio euismod lacinia at quis. Quis blandit turpis cursus in hac habitasse platea dictumst quisque."},
    { id: 6, date: `${timeStamp('2020', '5', '10', '0', '0')}`, heading: "Lorem Ipsum Drums", introduction:"Yt labore et dolore magna aliqua. Ullamcorper dignissim crolor morbi.", entry:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sed odio morbi quis commodo odio aenean sed adipiscing diam. Hendrerit gravida rutrum quisque non tellus orci ac. Maecenas ultricies mi eget mauris pharetra. Enim blandit volutpat maecenas volutpat blandit aliquam etiam. Sagittis aliquam malesuada bibendum arcu. Mauris pharetra et ultrices neque ornare. Pellentesque habitant morbi tristique senectus et netus et malesuada. Ullamcorper a lacus vestibulum sed arcu. Turpis tincidunt id aliquet risus feugiat. Risus viverra adipiscing at in tellus integer. Dui vivamus arcu felis bibendum ut. Non blandit massa enim nec dui nunc. Donec pretium vulputate sapien nec sagittis aliquam malesuada bibendum. Placerat vestibulum lectus mauris ultrices. Quis vel eros donec ac odio tempor. Non consectetur a erat nam at lectus urna duis. Tortor dignissim convallis aenean et tortor at risus. Facilisis volutpat est velit egestas dui id. Integer eget aliquet nibh praesent tristique magna sit amet. Lobortis feugiat vivamus at augue eget. Metus dictum at tempor commodo ullamcorper a. Sapien nec sagittis aliquam malesuada bibendum arcu vitae elementum. Elementum eu facilisis sed odio morbi quis commodo odio aenean. Hendrerit dolor magna eget est lorem. Non odio euismod lacinia at quis. Quis blandit turpis cursus in hac habitasse platea dictumst quisque."},
    { id: 7, date: `${timeStamp('2020', '6', '6', '12', '0')}`, heading: "Lorem Ipsum Color unudslkkdslkfjdsjkfjkcs cdfssewswededes dscdfdvfv vfdvfdvdfvdfvcdcdcdvf", introduction:"sed csdcdscsdcsddo eiusmod tempor incididunt ut labore et dolore magna aliqua. Ullamcorper dignissim crolor morbi.", entry:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sed odio morbi quis commodo odio aenean sed adipiscing diam. Hendrerit gravida rutrum quisque non tellus orci ac. Maecenas ultricies mi eget mauris pharetra. Enim blandit volutpat maecenas volutpat blandit aliquam etiam. Sagittis aliquam malesuada bibendum arcu. Mauris pharetra et ultrices neque ornare. Pellentesque habitant morbi tristique senectus et netus et malesuada. Ullamcorper a lacus vestibulum sed arcu. Turpis tincidunt id aliquet risus feugiat. Risus viverra adipiscing at in tellus integer. Dui vivamus arcu felis bibendum ut. Non blandit massa enim nec dui nunc. Donec pretium vulputate sapien nec sagittis aliquam malesuada bibendum. Placerat vestibulum lectus mauris ultrices. Quis vel eros donec ac odio tempor. Non consectetur a erat nam at lectus urna duis. Tortor dignissim convallis aenean et tortor at risus. Facilisis volutpat est velit egestas dui id. Integer eget aliquet nibh praesent tristique magna sit amet. Lobortis feugiat vivamus at augue eget. Metus dictum at tempor commodo ullamcorper a. Sapien nec sagittis aliquam malesuada bibendum arcu vitae elementum. Elementum eu facilisis sed odio morbi quis commodo odio aenean. Hendrerit dolor magna eget est lorem. Non odio euismod lacinia at quis. Quis blandit turpis cursus in hac habitasse platea dictumst quisque."},
    { id: 8, date: `${timeStamp('2020', '7', '1', '0', '0')}`, heading: "Lorem Ipsum Color unudslkkdslkfjdsjkfjkcs ", introduction:"sed csdcdscsdcsddo eiusmod tempor incididunt ut labore et dolore magna aliqua. Ullamcorper dignissim crolor morbi.", entry:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sed odio morbi quis commodo odio aenean sed adipiscing diam. Hendrerit gravida rutrum quisque non tellus orci ac. Maecenas ultricies mi eget mauris pharetra. Enim blandit volutpat maecenas volutpat blandit aliquam etiam. Sagittis aliquam malesuada bibendum arcu. Mauris pharetra et ultrices neque ornare. Pellentesque habitant morbi tristique senectus et netus et malesuada. Ullamcorper a lacus vestibulum sed arcu. Turpis tincidunt id aliquet risus feugiat. Risus viverra adipiscing at in tellus integer. Dui vivamus arcu felis bibendum ut. Non blandit massa enim nec dui nunc. Donec pretium vulputate sapien nec sagittis aliquam malesuada bibendum. Placerat vestibulum lectus mauris ultrices. Quis vel eros donec ac odio tempor. Non consectetur a erat nam at lectus urna duis. Tortor dignissim convallis aenean et tortor at risus. Facilisis volutpat est velit egestas dui id. Integer eget aliquet nibh praesent tristique magna sit amet. Lobortis feugiat vivamus at augue eget. Metus dictum at tempor commodo ullamcorper a. Sapien nec sagittis aliquam malesuada bibendum arcu vitae elementum. Elementum eu facilisis sed odio morbi quis commodo odio aenean. Hendrerit dolor magna eget est lorem. Non odio euismod lacinia at quis. Quis blandit turpis cursus in hac habitasse platea dictumst quisque."},
    { id: 9, date: `${timeStamp('2020', '8', '30', '11', '0')}`, heading: "Lorem Ipsum Drums", introduction:"Yt labore et dolore magna aliqua. Ullamcorper dignissim crolor morbi.", entry:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sed odio morbi quis commodo odio aenean sed adipiscing diam. Hendrerit gravida rutrum quisque non tellus orci ac. Maecenas ultricies mi eget mauris pharetra. Enim blandit volutpat maecenas volutpat blandit aliquam etiam. Sagittis aliquam malesuada bibendum arcu. Mauris pharetra et ultrices neque ornare. Pellentesque habitant morbi tristique senectus et netus et malesuada. Ullamcorper a lacus vestibulum sed arcu. Turpis tincidunt id aliquet risus feugiat. Risus viverra adipiscing at in tellus integer. Dui vivamus arcu felis bibendum ut. Non blandit massa enim nec dui nunc. Donec pretium vulputate sapien nec sagittis aliquam malesuada bibendum. Placerat vestibulum lectus mauris ultrices. Quis vel eros donec ac odio tempor. Non consectetur a erat nam at lectus urna duis. Tortor dignissim convallis aenean et tortor at risus. Facilisis volutpat est velit egestas dui id. Integer eget aliquet nibh praesent tristique magna sit amet. Lobortis feugiat vivamus at augue eget. Metus dictum at tempor commodo ullamcorper a. Sapien nec sagittis aliquam malesuada bibendum arcu vitae elementum. Elementum eu facilisis sed odio morbi quis commodo odio aenean. Hendrerit dolor magna eget est lorem. Non odio euismod lacinia at quis. Quis blandit turpis cursus in hac habitasse platea dictumst quisque."},
    { id: 10, date: `${timeStamp('2020', '9', '31', '19', '30')}`, heading: "Lorem Ipsum Drums", introduction:"Yt labore et dolore magna aliqua. Ullamcorper dignissim crolor morbi.", entry:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sed odio morbi quis commodo odio aenean sed adipiscing diam. Hendrerit gravida rutrum quisque non tellus orci ac. Maecenas ultricies mi eget mauris pharetra. Enim blandit volutpat maecenas volutpat blandit aliquam etiam. Sagittis aliquam malesuada bibendum arcu. Mauris pharetra et ultrices neque ornare. Pellentesque habitant morbi tristique senectus et netus et malesuada. Ullamcorper a lacus vestibulum sed arcu. Turpis tincidunt id aliquet risus feugiat. Risus viverra adipiscing at in tellus integer. Dui vivamus arcu felis bibendum ut. Non blandit massa enim nec dui nunc. Donec pretium vulputate sapien nec sagittis aliquam malesuada bibendum. Placerat vestibulum lectus mauris ultrices. Quis vel eros donec ac odio tempor. Non consectetur a erat nam at lectus urna duis. Tortor dignissim convallis aenean et tortor at risus. Facilisis volutpat est velit egestas dui id. Integer eget aliquet nibh praesent tristique magna sit amet. Lobortis feugiat vivamus at augue eget. Metus dictum at tempor commodo ullamcorper a. Sapien nec sagittis aliquam malesuada bibendum arcu vitae elementum. Elementum eu facilisis sed odio morbi quis commodo odio aenean. Hendrerit dolor magna eget est lorem. Non odio euismod lacinia at quis. Quis blandit turpis cursus in hac habitasse platea dictumst quisque."},
    { id: 11, date: `${timeStamp('2020', '10', '24', '19', '30')}`, heading: "Lorem Ipsum Drums", introduction:"Yt labore et dolore magna aliqua. Ullamcorper dignissim crolor morbi.", entry:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sed odio morbi quis commodo odio aenean sed adipiscing diam. Hendrerit gravida rutrum quisque non tellus orci ac. Maecenas ultricies mi eget mauris pharetra. Enim blandit volutpat maecenas volutpat blandit aliquam etiam. Sagittis aliquam malesuada bibendum arcu. Mauris pharetra et ultrices neque ornare. Pellentesque habitant morbi tristique senectus et netus et malesuada. Ullamcorper a lacus vestibulum sed arcu. Turpis tincidunt id aliquet risus feugiat. Risus viverra adipiscing at in tellus integer. Dui vivamus arcu felis bibendum ut. Non blandit massa enim nec dui nunc. Donec pretium vulputate sapien nec sagittis aliquam malesuada bibendum. Placerat vestibulum lectus mauris ultrices. Quis vel eros donec ac odio tempor. Non consectetur a erat nam at lectus urna duis. Tortor dignissim convallis aenean et tortor at risus. Facilisis volutpat est velit egestas dui id. Integer eget aliquet nibh praesent tristique magna sit amet. Lobortis feugiat vivamus at augue eget. Metus dictum at tempor commodo ullamcorper a. Sapien nec sagittis aliquam malesuada bibendum arcu vitae elementum. Elementum eu facilisis sed odio morbi quis commodo odio aenean. Hendrerit dolor magna eget est lorem. Non odio euismod lacinia at quis. Quis blandit turpis cursus in hac habitasse platea dictumst quisque."},
    { id: 12, date: `${timeStamp('2020', '11', '24', '19', '30')}`, heading: "Lorem Ipsum Drums", introduction:"Yt labore et dolore magna aliqua. Ullamcorper dignissim crolor morbi.", entry:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sed odio morbi quis commodo odio aenean sed adipiscing diam. Hendrerit gravida rutrum quisque non tellus orci ac. Maecenas ultricies mi eget mauris pharetra. Enim blandit volutpat maecenas volutpat blandit aliquam etiam. Sagittis aliquam malesuada bibendum arcu. Mauris pharetra et ultrices neque ornare. Pellentesque habitant morbi tristique senectus et netus et malesuada. Ullamcorper a lacus vestibulum sed arcu. Turpis tincidunt id aliquet risus feugiat. Risus viverra adipiscing at in tellus integer. Dui vivamus arcu felis bibendum ut. Non blandit massa enim nec dui nunc. Donec pretium vulputate sapien nec sagittis aliquam malesuada bibendum. Placerat vestibulum lectus mauris ultrices. Quis vel eros donec ac odio tempor. Non consectetur a erat nam at lectus urna duis. Tortor dignissim convallis aenean et tortor at risus. Facilisis volutpat est velit egestas dui id. Integer eget aliquet nibh praesent tristique magna sit amet. Lobortis feugiat vivamus at augue eget. Metus dictum at tempor commodo ullamcorper a. Sapien nec sagittis aliquam malesuada bibendum arcu vitae elementum. Elementum eu facilisis sed odio morbi quis commodo odio aenean. Hendrerit dolor magna eget est lorem. Non odio euismod lacinia at quis. Quis blandit turpis cursus in hac habitasse platea dictumst quisque."},
];

export default function Blog(props){
    const [hash, setHash] = useState(window.location.hash);
    //Handle events when URL hash changes and reload page without manually refresh page
    console.log(hash);
    const hashHandler = () => {
        setHash((prevHash) => {
            const newHash = window.location.hash;
            if(prevHash !== newHash){
                return newHash;
            }
            return prevHash;
        });
    };
    window.addEventListener('hashchange', hashHandler);

    return(
        <div>  
            <h2>My blog is currently under construction and I have no blog posts yet, so this is some mock data</h2>  
            {posts.map(post => {  
                console.log(posts.length);
                switch (window.location.hash) {
                    case `#${post.id}`:
                        return( <BlogPost id={post.id} image={Image} date={post.date} heading={post.heading} introduction={post.introduction} entry={post.entry} /> );                    
                    case '':                        
                        return(
                            <ul className="blog-posts">
                                <div className="blog-post-item" >
                                    <a id={post.id} href={`#${post.id}`}>
                                        <img src={Image} alt="Girl in a jacket" width="400" height="200" />
                                        <h1>{post.heading}</h1>      
                                    </a>
                                    <div className="time-stamp">
                                        <p id="blog-post-publish-date"><ClockIcon /> <time dateTime={post.date}>{post.date}</time></p>
                                    </div>
                                </div>
                            </ul>
                        );
                        default: return null                       
                }
            })} 
        </div>
    )
}

function timeStamp(yy, mm, dd, hour, minute){
    let today = new Date();

    //Adds a 0 to a number if number is less than 10, e.g 8 should be 08
    function addZero(num){
        return num < 10 ? `0${num}` : num;
    }

    today.setFullYear(yy);
    today.setMonth(mm);
    today.setDate(dd);

    today.setHours(hour);
    today.setMinutes(minute);

    let yr = today.getFullYear();
    let mo = addZero(today.getMonth() + 1);
    let da = addZero(today.getDate());
    let date = `${yr}-${mo}-${da}`;
    console.log(`Todays date is ${date}`);

    let hr = addZero(today.getHours());
    let min = addZero(today.getMinutes());
    let time = `${hr}:${min}`;
    console.log(`Current time is: ${time}`);

    return date + ' ' + time;
}